# Generated by Django 2.2.dev20181121224809 on 2018-11-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('published', models.DateField()),
                ('display_name', models.CharField(max_length=100)),
                ('img_filename', models.CharField(max_length=100)),
                ('scraped', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
